### ISSUE TITLE
It was return json response when press back button from the browser

### ISSUE THREAD

**Issue by tanagorns** [TypiCMS/Places#11]
<img width="648" alt="screen shot 2561-02-18 at 01 01 54" src="https://user-images.githubusercontent.com/1289708/36344071-66626f8c-1447-11e8-9ca3-414645e3726a.png">

<img width="363" alt="screen shot 2561-02-18 at 01 02 44" src="https://user-images.githubusercontent.com/1289708/36344073-7509c9cc-1447-11e8-9b68-390d4765a763.png">

I've check `request()->wantsJson()`, if content type is empty that was return `true`

**Comment by sdebacker** [comment]
Yes, that should be corrected, are you ready for a pull request ? I'm ok to receive it.
